FROM node:20.19.5-alpine3.22
WORKDIR /app
RUN npm install -g @angular/cli
COPY package*.json ./
RUN npm install
COPY ./scripts ./scripts

CMD ["sh", "-c", "npm run envs dev && ng serve --host 0.0.0.0"]
