services:
  ui:
    container_name: neura_web_prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "${PORT}:${PORT}"
    image: neura_web_prod
    restart: always
    env_file:
      - .env.prod
