FROM node:20.15.1-alpine3.20
WORKDIR /app
COPY package*.json ./
RUN npm install -g @angular/cli
RUN npm install
COPY ./scripts ./scripts

CMD ["sh", "-c", "npm run envs dev && ng serve --host 0.0.0.0"]
