FROM node:20.15.1-alpine3.20 AS build
WORKDIR /app
COPY package*.json .
COPY scripts .
RUN npm install
COPY . .
RUN npm run build

FROM node:20.15.1-alpine3.20
WORKDIR /app
COPY --from=build /app/dist/neura_web .
CMD ["node","server/server.mjs"]
