FROM node:20.15.1-alpine3.20 AS builder

WORKDIR /app

# Copiar los archivos package*.json
COPY package*.json ./

# Instalar las dependencias del proyecto
RUN npm ci

# Copiar el resto del código fuente
COPY . .

# Ejecutar la construcción del proyecto
RUN npm run envs prod && npm run build

FROM node:20.15.1-alpine3.20 AS runner
WORKDIR /app
COPY --from=builder /app/dist/neura_web .
CMD ["node","server/server.mjs"]
